//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_platformer p_platformer;
        
        private static SteamVR_Input_ActionSet_buggy p_buggy;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        private static SteamVR_Input_ActionSet_menuSet p_menuSet;
        
        private static SteamVR_Input_ActionSet_MovingBuildings p_MovingBuildings;
        
        private static SteamVR_Input_ActionSet_deleteBuildings p_deleteBuildings;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_platformer platformer
        {
            get
            {
                return SteamVR_Actions.p_platformer.GetCopy<SteamVR_Input_ActionSet_platformer>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggy buggy
        {
            get
            {
                return SteamVR_Actions.p_buggy.GetCopy<SteamVR_Input_ActionSet_buggy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        public static SteamVR_Input_ActionSet_menuSet menuSet
        {
            get
            {
                return SteamVR_Actions.p_menuSet.GetCopy<SteamVR_Input_ActionSet_menuSet>();
            }
        }
        
        public static SteamVR_Input_ActionSet_MovingBuildings MovingBuildings
        {
            get
            {
                return SteamVR_Actions.p_MovingBuildings.GetCopy<SteamVR_Input_ActionSet_MovingBuildings>();
            }
        }
        
        public static SteamVR_Input_ActionSet_deleteBuildings deleteBuildings
        {
            get
            {
                return SteamVR_Actions.p_deleteBuildings.GetCopy<SteamVR_Input_ActionSet_deleteBuildings>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_platformer = ((SteamVR_Input_ActionSet_platformer)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_platformer>("/actions/platformer")));
            SteamVR_Actions.p_buggy = ((SteamVR_Input_ActionSet_buggy)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_buggy>("/actions/buggy")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            SteamVR_Actions.p_menuSet = ((SteamVR_Input_ActionSet_menuSet)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_menuSet>("/actions/menuSet")));
            SteamVR_Actions.p_MovingBuildings = ((SteamVR_Input_ActionSet_MovingBuildings)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_MovingBuildings>("/actions/MovingBuildings")));
            SteamVR_Actions.p_deleteBuildings = ((SteamVR_Input_ActionSet_deleteBuildings)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_deleteBuildings>("/actions/deleteBuildings")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.platformer,
                    SteamVR_Actions.buggy,
                    SteamVR_Actions.mixedreality,
                    SteamVR_Actions.menuSet,
                    SteamVR_Actions.MovingBuildings,
                    SteamVR_Actions.deleteBuildings};
        }
    }
}
