//======================================= 2019, Stéphane Malta e Sousa, sitn-vr =======================================
//
// This script was generated by FME: 00_ImportAttributes
//
//=====================================================================================================================

using UnityEditor;
using UnityEngine;
using System.Collections.Generic;
using System;
using System.Text.RegularExpressions;

namespace SITN
{
    public class QueryableBuilding: MonoBehaviour
    {
        public string aire;
        public string altitude;
        public string owner;
        public string easements;

        public Dictionary<string, string> GetData()
        {
            return new Dictionary<string, string>() {
                { "Aire: ", aire},
                { "Altitude: ", altitude },
                { "Propriétaire: ", owner },
                { "Servitudes: ", easements },
            };
        }

        public override string ToString()
        {
            List<string> dataString = new List<string>();
            dataString.Add("<line-height=150%>Aire: " + aire + ", altitude: " + altitude);
            dataString.Add("<b><uppercase>Propriété de:</uppercase></b></line-height>");
            dataString.Add(Regex.Replace(owner, @" et ", "<br>") + "<line-height=150%>");
            dataString.Add("<b><uppercase>Servitudes:</uppercase></b></line-height>");
            dataString.Add("<align=justified>" + easements);
            return String.Join(Environment.NewLine, dataString.ToArray());
        }
    }
}
