//======================================= 2019, Stéphane Malta e Sousa, sitn-vr =======================================
//
// This script was generated by FME: shapefile2textline2
//
//=====================================================================================================================

using UnityEditor;
using UnityEngine;
using System.Collections.Generic;
using System;

namespace SITN
{
    public class QueryableBuilding: MonoBehaviour
    {
        public string aire;
        public string altitude;

        public Dictionary<string, string> GetData()
        {
            return new Dictionary<string, string>() {
                { "Aire: ", aire},
                { "Altitude: ", altitude }
            };
        }

        public override string ToString()
        {
            List<string> dataString = new List<string>();
            dataString.Add("Aire: " + aire);
            dataString.Add("Altitude: " + altitude);
            return String.Join(Environment.NewLine, dataString.ToArray());
        }
    }
}
